name: ML CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

permissions: write-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: iterative/setup-cml@v1

      - name: Prepare Environment
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy==1.23.5 scipy==1.9.3
          pip install scikit-learn==1.2.2 imbalanced-learn==0.10.1
          pip install -r requirements.txt

      - name: Run Training Script
        run: python script.py

      - name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## 📊 Model Training Report" > report.md

          echo "### Metrics" >> report.md
          awk 'NR%4{print "    " $0}{print ""}' metrics.txt >> report.md

          echo "### Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md

          cml comment create report.md

      - name: Save Model Artifact (MAIN only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: |
            model.pkl
            metrics.txt
            conf_matrix.png

        with:
          name: superstore-best-model
          path: super_store_pipeline_new.pkl

