name: CI/CD Superstore ML

on:
  pull_request:
    branches: [ "main" ]   # يشتغل فقط لو الـ PR متوجه لـ main
    paths-ignore:
      - 'README.md'        # اختياري: تجاهل التعديلات البسيطة

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/upload-artifact@v4

        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install seaborn matplotlib tabulate

      - name: Run Tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Run Training + Generate Report
        run: python train.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: superstore-best-model
          path: super_store_pipeline_new.pkl

      - name: Upload Report + Charts
        uses: actions/upload-artifact@v3
        with:
          name: superstore-report
          path: |
            report.md
            r2_comparison.png
            rmse_comparison.png
