name: CI/CD Superstore ML - Streamlit

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - 'README.md'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit seaborn matplotlib tabulate

      - name: Run Analysis + Generate Report
        run: python store_analysis.py

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Post Report as PR Comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## 📊 Model Training Report" > cml_report.md
          cat artifacts/report.md >> cml_report.md
          echo " " >> cml_report.md
          echo "### R2 Comparison" >> cml_report.md
          echo "![](./artifacts/r2_comparison.png)" >> cml_report.md
          echo " " >> cml_report.md
          echo "### RMSE Comparison" >> cml_report.md
          echo "![](./artifacts/rmse_comparison.png)" >> cml_report.md
          cml comment create cml_report.md





